// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label1;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Button7;
void ui_event_Image1(lv_event_t * e);
lv_obj_t * ui_Image1;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
void ui_event_Label3(lv_event_t * e);
lv_obj_t * ui_Label3;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label7;
void ui_event_Image2(lv_event_t * e);
lv_obj_t * ui_Image2;
void ui_event_Image3(lv_event_t * e);
lv_obj_t * ui_Image3;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Image8;

lv_obj_t * ui_Slider_record;

lv_obj_t * ui_Label_record_volume;

lv_obj_t * ui_Image_record_volume;
// lv_obj_t * ui_Image_record_volume;
void ui_event_Slider_record(lv_event_t * e);

void ui_event_record_volume(lv_event_t * e);
// void ui_event_Image_record_volume(lv_event_t * e);


// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t * ui_Screen3;
void ui_event_Button5(lv_event_t * e);
lv_obj_t * ui_Button5;
lv_obj_t * ui_Label5;
void ui_event_Button6(lv_event_t * e);
lv_obj_t * ui_Button6;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Container2;
void ui_event_Image5(lv_event_t * e);
lv_obj_t * ui_Image5;
void ui_event_Image4(lv_event_t * e);
lv_obj_t * ui_Image4;
void ui_event_Image6(lv_event_t * e);
void ui_event_Image_app_exit(lv_event_t * e);
lv_obj_t * ui_Image6;
lv_obj_t * ui_Slider1;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Image7;
lv_obj_t * ui_Image_app_exit;
lv_obj_t * ui_Label8;
void ui_event_Slider2(lv_event_t * e);
lv_obj_t * ui_Slider2;
lv_obj_t * ui_Label11;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);
    if(event_code == LV_EVENT_CLICKED) {
        exitfuction(e);
    }
}
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);
    if(event_code == LV_EVENT_CLICKED) {
        recordclicked(e);
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    }
}
void ui_event_Image1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);
    if(event_code == LV_EVENT_CLICKED) {
        imgbtnrecordfunction(e);
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    }
}
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);
    if(event_code == LV_EVENT_CLICKED) {
        stoprecordfunction(e);
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_Label3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);
    if(event_code == LV_EVENT_CLICKED) {
        stoprecordfunction(e);
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 100, &ui_Screen1_screen_init);
    }
}
void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);
    if(event_code == LV_EVENT_CLICKED) {
        pausefunction(e);
    }
}
void ui_event_Image2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);
    if(event_code == LV_EVENT_CLICKED) {
        imgbtnstoprecordfunction(e);
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_Image3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);
    if(event_code == LV_EVENT_CLICKED) {
        imgbtnpausefunction(e);
    }
}
void ui_event_record_volume(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);
    if(event_code == LV_EVENT_CLICKED) {
        recordvolumeclick(e);
    }
}
void ui_event_Slider_record(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);
    // if(event_code == LV_EVENT_RELEASED )
    // {
    //     recordvolumeslider(e);
    // }
    if(event_code == LV_EVENT_RELEASED )
    {
        recordvolumeslider(e);
    }
    else if(event_code == LV_EVENT_VALUE_CHANGED )
    {
        record_showvolumeslider(e);
    }
}
void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);
    if(event_code == LV_EVENT_CLICKED) {
        playaudiocallback(e);
    }
}
void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);
    if(event_code == LV_EVENT_CLICKED) {
        playaudioexit(e);
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_Image5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);
    if(event_code == LV_EVENT_CLICKED) {
        playvolumeclick(e);
    }
}
void ui_event_Image4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);
    if(event_code == LV_EVENT_CLICKED) {
        playclickedscreen3(e);
    }
}
void ui_event_Image6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);
    if(event_code == LV_EVENT_CLICKED) {
        playscreen3exit(e);
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_Image_app_exit(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);
    if(event_code == LV_EVENT_CLICKED) {
        app_exit_imgbtn(e);
    }
}
void ui_event_Slider2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);
    if(event_code == LV_EVENT_RELEASED )
    {
        playvolumeslider(e);
    }
    else if(event_code == LV_EVENT_VALUE_CHANGED )
    {
        showvolumeslider(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
