// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Button7;
void ui_event_Image1(lv_event_t * e);
extern lv_obj_t * ui_Image1;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
void ui_event_Label3(lv_event_t * e);
extern lv_obj_t * ui_Label3;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label7;
void ui_event_Image2(lv_event_t * e);
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image_app_exit;
extern lv_obj_t * ui_Slider_record;
extern lv_obj_t * ui_Label_record_volume;
// extern lv_obj_t * ui_Image_record_volume;
void ui_event_Image3(lv_event_t * e);
// void ui_event_Image_record_volume(lv_event_t * e)

void ui_event_Slider_record(lv_event_t * e);
extern lv_obj_t * ui_Image_record_volume;
void ui_event_record_volume(lv_event_t * e);

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label5;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Container2;
void ui_event_Image5(lv_event_t * e);
extern lv_obj_t * ui_Image5;
void ui_event_Image4(lv_event_t * e);
extern lv_obj_t * ui_Image4;
void ui_event_Image6(lv_event_t * e);

void ui_event_Image_app_exit(lv_event_t * e);
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Label8;
void ui_event_Slider2(lv_event_t * e);
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui____initial_actions0;








void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
