id: switch_led
name: switch_led
name[zh]: 板载LED闪烁
version: 1.0.0
#icon: assets/hello.png
author: hqy1433
desc: Using GPIO14 to control onboard LED flashing
desc[zh]: 使用GPIO14控制板载LED闪烁
files:
  # assets: assets

