// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
// #include "all_btn_ui.h"
#include "../imgbtn_ui/all_btn_ui.h"
void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button3 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button3, 100);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_x(ui_Button3, 213);
    lv_obj_set_y(ui_Button3, -137);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, 1);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "stop");

    ui_Button4 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button4, 100);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_x(ui_Button4, 216);
    lv_obj_set_y(ui_Button4, -71);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 1);
    lv_obj_set_y(ui_Label4, 0);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "pause");

    ui_Label7 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 0);
    lv_obj_set_y(ui_Label7, 63);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "record");

    ui_Image2 = lv_imagebutton_create(ui_Screen2);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_imagebutton_set_src(ui_Image2, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &imgbtn_record_over, NULL);
    lv_imagebutton_set_src(ui_Image2, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &imgbtn_record_over, NULL);
    lv_obj_set_x(ui_Image2, -1);
    lv_obj_set_y(ui_Image2, 141);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CHECKABLE);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_imagebutton_create(ui_Screen2);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_imagebutton_set_src(ui_Image3, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &imgbtn_record_play, NULL);
    lv_imagebutton_set_src(ui_Image3, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &imgbtn_record_pause, NULL);
    lv_obj_set_x(ui_Image3, 215);
    lv_obj_set_y(ui_Image3, 142);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CHECKABLE);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label12 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -3);
    lv_obj_set_y(ui_Label12, -153);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);

    ui_Image8 = lv_imagebutton_create(ui_Screen2);
    lv_obj_set_width(ui_Image8, 150);
    lv_obj_set_height(ui_Image8, 150);
    lv_imagebutton_set_src(ui_Image8, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &img_show_record, NULL);
    lv_imagebutton_set_src(ui_Image8, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &img_show_record, NULL);
    lv_obj_set_x(ui_Image8, 2);
    lv_obj_set_y(ui_Image8, -56);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_CHECKABLE);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


    ui_Image_record_volume = lv_imagebutton_create(ui_Screen2);
    lv_obj_set_width(ui_Image_record_volume, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Image_record_volume, LV_SIZE_CONTENT);
    lv_imagebutton_set_src(ui_Image_record_volume, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &volume_imgbtn, NULL);
    lv_imagebutton_set_src(ui_Image_record_volume, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &volume_imgbtn, NULL);
    lv_obj_set_x(ui_Image_record_volume, -182);
    lv_obj_set_y(ui_Image_record_volume, 140);
    lv_obj_add_flag(ui_Image_record_volume, LV_OBJ_FLAG_CHECKABLE);
    lv_obj_set_align(ui_Image_record_volume, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_record_volume, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_record_volume, LV_OBJ_FLAG_SCROLLABLE);      /// Flags



    ui_Slider_record = lv_slider_create(ui_Screen2);
    lv_slider_set_range(ui_Slider_record, 0, 24);  // 最小值0，最大值24
    lv_slider_set_value(ui_Slider_record, 20, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider_record) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider_record, 20, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider_record, 17);
    lv_obj_set_height(ui_Slider_record, 161);
    lv_obj_set_x(ui_Slider_record, -187);
    lv_obj_set_y(ui_Slider_record, -57);
    lv_obj_set_align(ui_Slider_record, LV_ALIGN_CENTER);

    ui_Label_record_volume = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label_record_volume, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_record_volume, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_record_volume, -225);
    lv_obj_set_y(ui_Label_record_volume, -38);
    lv_obj_set_align(ui_Label_record_volume, LV_ALIGN_CENTER);

    lv_slider_set_value(ui_Slider_record, 20, LV_ANIM_OFF); // Set initial value
    char buf_play[4];
    lv_snprintf(buf_play, sizeof(buf_play), "%d", lv_slider_get_value(ui_Label_record_volume));
    lv_label_set_text(ui_Label_record_volume, buf_play);


    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_Label3, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_Label4, LV_OBJ_FLAG_HIDDEN);

    lv_obj_add_flag(ui_Slider_record, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_Label_record_volume, LV_OBJ_FLAG_HIDDEN);


    lv_obj_add_event_cb(ui_Label3, ui_event_Label3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image2, ui_event_Image2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image3, ui_event_Image3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image_record_volume, ui_event_record_volume, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider_record, ui_event_Slider_record, LV_EVENT_ALL, NULL);

}
