// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "../imgbtn_ui/all_btn_ui.h"
// #include "all_btn_ui.h"
void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x4C4E5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen1, lv_color_hex(0x393B46), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button1, 100);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, 218);
    lv_obj_set_y(ui_Button1, -85);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -3);
    lv_obj_set_y(ui_Label1, 0);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "exit");

    ui_Button2 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button2, 100);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_x(ui_Button2, 217);
    lv_obj_set_y(ui_Button2, -150);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -1);
    lv_obj_set_y(ui_Label2, 0);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "record");

    ui_Button7 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button7, 100);
    lv_obj_set_height(ui_Button7, 50);
    lv_obj_set_x(ui_Button7, -786);
    lv_obj_set_y(ui_Button7, 29);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_imagebutton_create(ui_Screen1);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_imagebutton_set_src(ui_Image1, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &imgbtn_record, NULL);
    lv_imagebutton_set_src(ui_Image1, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &imgbtn_record, NULL);

    lv_obj_set_x(ui_Image1, -1);
    lv_obj_set_y(ui_Image1, 141);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CHECKABLE);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


    ui_Image_app_exit = lv_imagebutton_create(ui_Screen1);
    lv_obj_set_width(ui_Image_app_exit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_app_exit, LV_SIZE_CONTENT);    /// 1
    lv_imagebutton_set_src(ui_Image_app_exit, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &exit_ima_btn, NULL);
    lv_imagebutton_set_src(ui_Image_app_exit, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &exit_ima_btn, NULL);

    lv_obj_set_x(ui_Image_app_exit, 198);
    lv_obj_set_y(ui_Image_app_exit, 142);
    lv_obj_add_flag(ui_Image_app_exit, LV_OBJ_FLAG_CHECKABLE);
    lv_obj_set_align(ui_Image_app_exit, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_app_exit, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_app_exit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_add_flag(ui_Label1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_add_flag(ui_Label2, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image1, ui_event_Image1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image_app_exit, ui_event_Image_app_exit, LV_EVENT_ALL, NULL);

}
