// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project
#include "../ui.h"
#include "../imgbtn_ui/all_btn_ui.h"
// #include "all_btn_ui.h"
void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button5 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button5, 100);
    lv_obj_set_height(ui_Button5, 50);
    lv_obj_set_x(ui_Button5, 206);
    lv_obj_set_y(ui_Button5, -59);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -1);
    lv_obj_set_y(ui_Label5, 3);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "start");

    ui_Button6 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button6, 100);
    lv_obj_set_height(ui_Button6, 50);
    lv_obj_set_x(ui_Button6, 209);
    lv_obj_set_y(ui_Button6, -120);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -3);
    lv_obj_set_y(ui_Label6, 1);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "exit");

    ui_Container2 = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 553);
    lv_obj_set_height(ui_Container2, 368);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_imagebutton_create(ui_Container2);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_imagebutton_set_src(ui_Image5, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &volume_imgbtn, NULL);
    lv_imagebutton_set_src(ui_Image5, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &volume_imgbtn, NULL);
    lv_obj_set_x(ui_Image5, -166);
    lv_obj_set_y(ui_Image5, 121);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_CHECKABLE);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_imagebutton_create(ui_Container2);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_imagebutton_set_src(ui_Image4, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &play_imgbtn, NULL);
    lv_imagebutton_set_src(ui_Image4, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &pause_imgbtn, NULL);
    lv_obj_set_x(ui_Image4, 0);
    lv_obj_set_y(ui_Image4, 121);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CHECKABLE);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_imagebutton_create(ui_Container2);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_imagebutton_set_src(ui_Image6, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &exit_ima_btn, NULL);
    lv_imagebutton_set_src(ui_Image6, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &exit_ima_btn, NULL);
    lv_obj_set_x(ui_Image6, 165);
    lv_obj_set_y(ui_Image6, 122);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_CHECKABLE);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Slider1 = lv_slider_create(ui_Container2);
    lv_slider_set_value(ui_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 347);
    lv_obj_set_height(ui_Slider1, 10);
    lv_obj_set_x(ui_Slider1, -1);
    lv_obj_set_y(ui_Slider1, 54);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);


    ui_Label9 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -225);
    lv_obj_set_y(ui_Label9, 52);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);

    ui_Label10 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 208);
    lv_obj_set_y(ui_Label10, 51);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);

    ui_Image7 = lv_imagebutton_create(ui_Container2);
    lv_obj_set_width(ui_Image7, 150);
    lv_obj_set_height(ui_Image7, 150);
    lv_imagebutton_set_src(ui_Image7, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &audio_img_static, NULL);
    lv_imagebutton_set_src(ui_Image7, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &audio_img_static, NULL);
    lv_obj_set_x(ui_Image7, -7);
    lv_obj_set_y(ui_Image7, -61);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_CHECKABLE);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -9);
    lv_obj_set_y(ui_Label8, -159);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "audio");

    ui_Slider2 = lv_slider_create(ui_Screen3);
    lv_slider_set_range(ui_Slider2, 0, 32);  
    lv_slider_set_value(ui_Slider2, 25, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 25, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 17);
    lv_obj_set_height(ui_Slider2, 161);
    lv_obj_set_x(ui_Slider2, -176);
    lv_obj_set_y(ui_Slider2, -74);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);





    ui_Label11 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -214);
    lv_obj_set_y(ui_Label11, -65);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);


    lv_obj_add_flag(ui_Slider2, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_Label11, LV_OBJ_FLAG_HIDDEN);

    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_HIDDEN);

    lv_slider_set_value(ui_Slider2, 50, LV_ANIM_OFF); // Set initial value
    char buf_play[4];
    lv_snprintf(buf_play, sizeof(buf_play), "%d", lv_slider_get_value(ui_Slider2));
    lv_label_set_text(ui_Label11, buf_play);

    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image5, ui_event_Image5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image4, ui_event_Image4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image6, ui_event_Image6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider2, ui_event_Slider2, LV_EVENT_ALL, NULL);

}
