// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_btn1 = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_btn1, 100);
lv_obj_set_height( ui_btn1, 50);
lv_obj_set_x( ui_btn1, 100 );
lv_obj_set_y( ui_btn1, -31 );
lv_obj_set_align( ui_btn1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btn1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Arc1 = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_Arc1, 150);
lv_obj_set_height( ui_Arc1, 150);
lv_obj_set_x( ui_Arc1, -52 );
lv_obj_set_y( ui_Arc1, -26 );
lv_obj_set_align( ui_Arc1, LV_ALIGN_CENTER );


ui_Label1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -54 );
lv_obj_set_y( ui_Label1, 80 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Hello LVGL");

ui_btn2 = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_btn2, 100);
lv_obj_set_height( ui_btn2, 50);
lv_obj_set_x( ui_btn2, 100 );
lv_obj_set_y( ui_btn2, 37 );
lv_obj_set_align( ui_btn2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btn2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_btn1, ui_event_btn1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btn2, ui_event_btn2, LV_EVENT_ALL, NULL);

}
